# Generated by Django 3.1.4 on 2021-05-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210508_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='AppointmentDate1',
        ),
    ]
