# Generated by Django 3.1.4 on 2021-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_appointment_appointmentdate1'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='AppointmentDate1',
            field=models.DateField(auto_now=True),
        ),
    ]
