# Generated by Django 3.1.4 on 2021-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20210508_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Message', models.CharField(max_length=70)),
            ],
        ),
    ]
