# Generated by Django 3.1.4 on 2021-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210518_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentDate',
            field=models.DateField(),
        ),
    ]
