# Generated by Django 3.1.4 on 2021-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210529_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
