# Generated by Django 3.1.4 on 2021-05-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20210529_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Gender',
        ),
    ]
