# Generated by Django 3.1.4 on 2021-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20210529_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
