# Generated by Django 3.1.4 on 2021-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Gender',
            field=models.CharField(default='female', max_length=10),
            preserve_default=False,
        ),
    ]
