# Generated by Django 3.1.4 on 2021-06-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('compound_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medicines_list'),
        ),
    ]
