# Generated by Django 3.1.4 on 2021-06-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20210601_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
    ]
